name = "chesspro-api"
main = "worker/src/index.ts"
compatibility_date = "2025-12-31"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" },
  { name = "HUB", class_name = "Hub" },
  { name = "MATCH", class_name = "Matchmaking" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room", "Hub", "Matchmaking"]

[[d1_databases]]
binding = "DB"
database_name = "chesspro"
database_id = "86b2fe84-996a-4010-9f29-569aa293938f"
migrations_dir = "migrations"

[vars]
TOKEN_TTL_SECONDS = "604800"
